baseurl = "https://fadastra.xyz/"
languageCode = "en-US"
title = "Jeffrey Simpson"
theme = "hallo"

[Author]
    name = "Jeffrey Simpson"

[params]
  avatar = "profile.jpg"
  author = "Jeffrey Simpson"
  [[params.links]]
      icon = "fas fa-envelope"
      title = "Email"
      url = "mailto:jeffrey.simpson@unsw.edu.au"
  [[params.links]]
      icon = "fab fa-twitter"
      title = "Twitter"
      url = "https://twitter.com/fadastra"
  [[params.links]]
      icon = "fab fa-github"
      title = "Github"
      url = "https://github.com/jeffreysimpson"
  [[params.links]]
      icon = "ai ai-ads"
      title = "ADS"
      url = "https://ui.adsabs.harvard.edu/#search/q=orcid%3A0000-0002-8165-2507"
