baseurl = ""
languageCode = "en-US"
title = "Jeffrey Simpson"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "hugo-sustain"

[permalinks]
  post = "/:year/:month/:day/:slug"

[params]
  avatar = "profile.jpg"
  author = "Jeffrey Simpson"
  description = "Describe your website"

  # Custom assets can be linked with their paths relative to static/
  custom_css = []
  custom_js  = []

[params.social]
  Email         = "jeffrey.simpson@unsw.edu.au"
  Twitter       = "fadastra"
  Github        = "jeffreysimpson"
  ADS           = "0000-0002-8165-2507"
  # Stackoverflow = "username"
  # Medium        = "username"
  # Telegram      = "username"

## Main Menu
[[menu.main]]
  name = "Email"
  weight = 100
  identifier = "email"
  url = "mailto:jeffrey.simpson@unsw.edu.au"
[[menu.main]]
    name = "Twitter"
    weight = 100
    identifier = "Twitter"
    url = "https://twitter.com/fadastra"
[[menu.main]]
    name = "CV"
    weight = 100
    identifier = "CV"
    url = "cv.pdf"
# [[menu.main]]
#   name = "projects"
#   identifier = "projects"
#   weight = 200
#   url = "/projects/"
# [[menu.main]]
#   name = "resume"
#   identifier = "resume"
#   weight = 300
#   url = "/resume/"
